ARG NODE_VERSION=22.14.0

FROM node:${NODE_VERSION}-slim AS base

ARG PORT=3000

WORKDIR /app

# Build
FROM base AS build

RUN corepack enable
COPY --link package.json pnpm-lock.yaml ./
RUN pnpm install

# Run
FROM base

RUN corepack enable

ENV PORT=$PORT
ENV NODE_ENV=development

COPY --from=build /app/node_modules /app/node_modules

CMD [ "pnpm", "run", "dev" ]